FROM php:cli-alpine
# RUN cp "/usr/local/etc/php/php.ini-production" "/usr/local/etc/php/php.ini"
RUN apk update && apk add bash \
    curl \
    unzip

# composer
RUN curl -s https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer
RUN composer global require squizlabs/php_codesniffer
RUN composer global require friendsofphp/php-cs-fixer
RUN ln -s /root/.composer/vendor/bin/phpcs /usr/local/bin/phpcs && \
    ln -s /root/.composer/vendor/bin/phpcbf /usr/local/bin/phpcbf && \
    ln -s /root/.composer/vendor/bin/php-cs-fixer /usr/local/bin/php-cs-fixer

COPY ./php.ini /usr/local/etc/php/php.ini
